- id: collection-desc-validator
  name: Collection Description Validator
  description: Check description of collections against schemas
  entry: collection-desc-validator
  always_run: true
  pass_filenames: false
  verbose: true
  language: python
