- id: item-desc-validator
  name: Item Description Validator
  description: Check description of items against schemas
  entry: item-desc-validator
  always_run: true
  pass_filenames: false
  verbose: true
  language: python
